#!/bin/bash

CURRENT_TIME=`date +"%m-%d-%y"`
CONFIG_FILE='backpack.conf'
while IFS= read -r line
do
  username=`echo $line | cut -d ' ' -f1`
  ip=`echo $line | cut -d ' ' -f2`
  #Must run duplicity for each file path you want to back
  includes=`echo $line | cut -d ' ' -f3 | tr ":" " "`
  excludes=`echo $line | cut -d ' ' -f4 | tr ":" " "`
#  if [[ "$includes" ]]
#  then
#    includes=`echo "$includes" | sed -e 's/\( \)/\1 --include /g'`
#  fi
  if [[ "$excludes" ]]
  then
    excludes=`echo " $excludes" | sed -e 's/\( \)/\1 --exclude /g'`
  fi

  #The correct duplicity command
  ssh $ip "duplicity --asynchronous-upload --no-encryption --no-print-statistics $includes $excludes gdocs://silverbulletapps:cs180rocks@gmail.com/$username/$CURRENT_TIME" < /dev/null
  echo $ip
done < "$CONFIG_FILE"
