#!/bin/bash

CURRENT_TIME=`date +"%m-%d-%y"`
CONFIG_FILE='backpack.conf'
echo Parsing config file: $CONFIG_FILE
while IFS= read -r line
do
  username=`echo $line | cut -d ' ' -f1`
  ip=`echo $line | cut -d ' ' -f2`
  #Must run duplicity for each file path you want to back
  includes=`echo $line | cut -d ' ' -f3 | tr ":" " "`
  excludes=`echo $line | cut -d ' ' -f4 | tr ":" " "`
  #The correct duplicity command
  echo 'duplicity --asynchronous-upload --no-encryption --no-print-statistics '$includes' gdocs://silverbulletapps@gmail.com/'$username'/'$CURRENT_TIME
done < "$CONFIG_FILE" 
